# Generated by Django 3.1.2 on 2020-10-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20201001_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note_type',
            field=models.CharField(choices=[('R', 'Random'), ('N', 'Not Important'), ('M', 'Most Important')], max_length=30),
        ),
    ]
