# Generated by Django 3.1.2 on 2020-11-27 07:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_note_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='created_date',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2020, 11, 27, 7, 50, 32, 910231)),
        ),
    ]
